### ISSUE TITLE
Вопрос: как реализовано требование

### ISSUE THREAD

**Issue by oknoproblem** [oknoproblem/medo_agent#10]
> При регистрации сформированного субъектом МЭДО сообщения должны фиксироваться следующие данные:
> - дата и время передачи сообщения адресатам.

Данное требование указано в ТЗ, каким образом оно реализовано?

**Comment by ikudin** [comment]
дата и время передачи адресатам - это время, когда письмо получает статус 4 (доставлено)

**Comment by oknoproblem** [comment]
ок
