### ISSUE TITLE
На карточке заявки отсутствует реквизит "Заявитель"

### ISSUE THREAD

**Issue by oknoproblem** [oknoproblem/medo_agent#100]
На карточке заявки отсутствует реквизит "Заявитель", см. прототип.

На карточке заявки данный реквизит должен быть, заполнятся должен ФИО пользователя создавшего заявку.

**Comment by ikudin** [comment]
Реквизит "Податель"

**Comment by oknoproblem** [comment]
дам, Податель, откуда у меня взялся Заявитель не понимаю.

Всё ок.
