### ISSUE TITLE
Карточка квитанции не содержит ссылки на документ.

### ISSUE THREAD

**Issue by oknoproblem** [oknoproblem/medo_agent#109]
```
<?xml version="1.0" encoding="windows-1251"?>
<xdms:communication xdms:version="2.6" xmlns:xdms="http://www.infpres.com/IEDMS" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<xdms:header xdms:type="Квитанция" xdms:uid="4C0F77DC-2AEF-4A38-A44F-57B917089213" xdms:created="2014-11-14T13:33:57">
		<xdms:source xdms:uid="a2cc06ba-a4a2-4d9c-88f9-000000000002">
			<xdms:organization>Федеральное Казначейство</xdms:organization>
		</xdms:source>
	</xdms:header>
	<xdms:acknowledgment xdms:uid="68B2871F-BC0A-451B-0000-000000000100" xdms:content="document">
		<xdms:time>2014-11-14T13:33:57</xdms:time>
		<xdms:accepted>true</xdms:accepted>
	</xdms:acknowledgment>
</xdms:communication>
```
документ с guid 68B2871F-BC0A-451B-0000-000000000100 присутствует в системе.

Соответственно должна быть ссылка на документ на карточке, ссылки нет:
![001](https://cloud.githubusercontent.com/assets/6616341/16798307/1b4ff962-48f4-11e6-93bf-da358456e18d.png)

**Comment by oknoproblem** [comment]
Кстати, не заполняется "Статус МЭДО"

**Comment by ikudin** [comment]
Не понял, откуда это взялось?
В прототипе никаких ссылок нет.
А все остальное норм, сделано

**Comment by oknoproblem** [comment]
![001](https://cloud.githubusercontent.com/assets/6616341/17091408/d1d12eca-5242-11e6-9080-abdb80635b63.png)

**Comment by oknoproblem** [comment]
И Статус МЭДО не заполняется.

**Comment by oknoproblem** [comment]
пропустил багу...

- Номер документа должен заполняться № документа, а не GUID документа
- некорректный формат времени Дата регистрации
- "Дата доставки" - дата из :
```
	<xdms:acknowledgment xdms:uid="68B2871F-BC0A-451B-0000-000000000100" xdms:content="document">
		<xdms:time>2014-11-14T13:33:57</xdms:time>
```
![001](https://cloud.githubusercontent.com/assets/6616341/17481191/68169266-5d84-11e6-8694-3513de588998.png)

**Comment by ikudin** [comment]
1. номер будет номером,если такой документ будет в системе. В противном случае - гуид
2. испарвил
3. исправил

**Comment by oknoproblem** [comment]
в последней сборке изменений нет.

**Comment by ikudin** [comment]
не понял. как это нет? дата тоже не в правильном формате?

**Comment by oknoproblem** [comment]
ok
