### ISSUE TITLE
Подготовить документ с новыми требованиями для официального согласования изменения ТЗ

### ISSUE THREAD

**Issue by oknoproblem** [oknoproblem/medo_agent#11]
Имеется ввиду следующее:

1) Проверка xml (все виды)
2) Обработка транспортного контэйнера
3) Новый тип инцидента при получении сообщения типов "Уведомление", "Квитанция" по документу отсутствующему в БД

**Comment by ikudin** [comment]
а если в системе появляется письмо, которое не отправлялось, но уже доставлено, то это тоже инцидент?
имеется в виду период ввода в эксплуатацию, когда не все исходящие письма записываются к нам

**Comment by oknoproblem** [comment]
я пока не задавал этот вопрос Андрею.

**Comment by oknoproblem** [comment]
Документ в данный момент не нужен, решили ПиМИ делать как в ТЗ, все дополнения идут не официально.
