### ISSUE TITLE
Ошибка разбора Уведомления "Отказано в регистрации"

### ISSUE THREAD

**Issue by oknoproblem** [oknoproblem/medo_agent#114]
отправил Уведомление:
```
<?xml version="1.0" encoding="windows-1251"?>
<xdms:communication xdms:version="2.2" xmlns:xdms="http://www.infpres.com/IEDMS" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<xdms:header xdms:type="Уведомление" xdms:uid="67B1A44C-957F-4E64-A82D-000000000152" xdms:created="2016-03-02T15:45:01">
		<xdms:source xdms:uid="a2cc06ba-a4a2-4d9c-88f9-000000000002">
			<xdms:organization>Федеральное Казначейство</xdms:organization>
		</xdms:source>
	</xdms:header>
	<xdms:notification xdms:type="Отказано в регистрации" xdms:uid="68B2871F-BC0A-451B-0000-000000000102" xdms:id="bf5662c8-70e2-427e-ba4d-000000000152">
		<xdms:documentRefused>
			<xdms:time>2016-03-02T15:44:24</xdms:time>
			<xdms:foundation>
				<xdms:organization>Минкомсвязь</xdms:organization>
				<xdms:person>Алхазов Дмитрий Михайлович</xdms:person>
				<xdms:num>
					<xdms:number>102</xdms:number>
					<xdms:date>2016-03-02</xdms:date>
				</xdms:num>
			</xdms:foundation>
			<xdms:reason>Ошибка адресации</xdms:reason>
		</xdms:documentRefused>
	</xdms:notification>
</xdms:communication>
```
на документ.

При разборе данного уведомления создался инцидент:

> Ошибка при обработке папки good_notification_ForbidenForRegistration_68B2871F-BC0A-451B-0000-000000000100. 
> Нарушена структура файла с описанием в файле D:\MEDO\Portal\Monitoring Agent MEDO\MailFromMin\ToSend\good_notification_ForbidenForRegistration_68B2871F-BC0A-451B-0000-000000000100\notification.XML. 
> Ссылка на объект не указывает на экземпляр объекта. 
> Ссылка на объект не указывает на экземпляр объекта.

Уведомление корректно с точки зрения XSD и насколько я понимаю " Ссылка на объект не указывает на экземпляр объекта" ошибка у тебя в агенте.

**Comment by ikudin** [comment]
[https://github.com/oknoproblem/medo_agent/issues/91](url)

**Comment by oknoproblem** [comment]
ок
