### ISSUE TITLE
при наличии инцидента в сообщении создаётся два инцидента

### ISSUE THREAD

**Issue by oknoproblem** [oknoproblem/medo_agent#115]
при наличии инцидента в сообщении создаётся два инцидента
![001](https://cloud.githubusercontent.com/assets/6616341/17329051/7c55f1b4-58c9-11e6-8f33-03af6cbd6e05.png)
и второй без ссылки на сообщение:
![001](https://cloud.githubusercontent.com/assets/6616341/17329068/941ae246-58c9-11e6-8133-9752962809a2.png)

**Comment by ikudin** [comment]
Должно работать. 

Ошибка происходила из-за того, что сначала агент регистрировал инцидент, не зная номера письма в БД, а потом при отправке данных о письме на сервер(вместе с ошибками разбора) регистрировался инцидент с номером письма.

в данный момент инциденты, связанные с письмами регистрируются сервером, ~~что бы это не значило~~
расписал все для себя, так что не вникайте)

**Comment by oknoproblem** [comment]
ok
