### ISSUE TITLE
Нужен скрипт по созданию пользователя на пустой БД

### ISSUE THREAD

**Issue by oknoproblem** [oknoproblem/medo_agent#116]
Нужен скрипт по созданию пользователя на пустой БД

Необходимость развёртывания новой БД ты сам обосновал при изменении порядка статусов, необходимо заново развернуть БД, нужна инструкция и скрипты первичного наполнения.

**Comment by ikudin** [comment]
если удалить базу и запустить приложение, то по умолчанию создается начальное заполнение со всеми типами сообщений, заявок и тд.
и пользователь user/password тоже. и уже после запуска можно всем управлять из интерфейса

**Comment by oknoproblem** [comment]
пользователь не создаётся.
при этом зайти под user/password можно, но список пользователей пуст и создать нового пользователя нельзя.

**Comment by oknoproblem** [comment]
я понял в чём дело, пользователя user не видно в списке, я пытался создать такого-же ошибка не выводилась.
Продолжу на новой БД
