### ISSUE TITLE
Время регистрации статусов СЭД 00:00:00

### ISSUE THREAD

**Issue by oknoproblem** [oknoproblem/medo_agent#117]
Время регистрации статусов СЭД всегда 00:00:00. Должно быть текущее время.
см. скрин
![001](https://cloud.githubusercontent.com/assets/6616341/17477473/2e1614bc-5d6e-11e6-914e-8cac31bb7565.png)

**Comment by ikudin** [comment]
какое текущее?
я ж дату беру из хмл

**Comment by oknoproblem** [comment]
А ну да, правильно, но ты берёшь не ту дату, надо эту:
`			<xdms:time>2016-03-02T15:44:24</xdms:time>`

**Comment by oknoproblem** [comment]
ну или 
`<xdms:header xdms:type="Уведомление" xdms:uid="67B1A44C-957F-4E64-A82D-000000000141" xdms:created="2016-03-02T15:45:01">`
на худой конец, в любом случае у тебя не отображается время, хотя оно указано.

**Comment by ikudin** [comment]
я дату брал из даты документа.
по ходу)
сейчас взял из time. должно работать.

**Comment by oknoproblem** [comment]
ошибка при обработке любого уведомления:
```
Ошибка при обработке папки D:\MEDO\Portal\Monitoring Agent MEDO\MailFromMin\ToSend\good_notification_documentRefused_68B2871F-BC0A-451B-0000-000000000100. 
Нарушена структура файла с описанием в файле D:\MEDO\Portal\Monitoring Agent MEDO\MailFromMin\ToSend\good_notification_documentRefused_68B2871F-BC0A-451B-0000-000000000100\notification.XML. 
Ссылка на объект не указывает на экземпляр объекта. 
Ссылка на объект не указывает на экземпляр объекта.
```

**Comment by oknoproblem** [comment]
ok
