### ISSUE TITLE
На больших объёмах данных, вывод списка сообщений/инцидентов тормозит

### ISSUE THREAD

**Issue by oknoproblem** [oknoproblem/medo_agent#118]
На больших объёмах данных, вывод списка сообщений/инцидентов тормозит (хотя странно, мы же специально делали вывод только 20 первых записей).

Необходимо либо избавится от тормозов, либо сделать "прогрессбар".

Большие объёмы данных есть только на вашем стенде, так что предлагаю там и смотреть.

**Comment by ikudin** [comment]
да, я тоже подумал о том, что не должно тупить, так как выводим всего 20 записей.
но. я предупреждал об этом (и уже говорил об этом).
Например, при поиске писем с инцидентами(или заявками) мы должны просчитать у КАЖДОГО письма кол-во этих самых заявок. если хранить статически в поле таблицы кол-во заявок (или инцидентов) то непонятно, уменьшать кол-во при выполнении или оставлять. короче говоря, неизвестно, к чему это решение приведет, так как изменятся все компоненты.

на данный момент поменял порядок формирования списка заявок, надо будет смотреть, как изменится ситуация

**Comment by oknoproblem** [comment]
вроде ок на 500 000 записях.
