### ISSUE TITLE
В поле sender сообщения записывается значение параметра Email настройки агента мониторинга

### ISSUE THREAD

**Issue by oknoproblem** [oknoproblem/medo_agent#12]
шаги:
- положить в папку отправки агента мониторинга корректное сообщение в ini файла которого отправитель отличается (например "gu~gu") от значения указанного в настройках агента мониторинга

> <common>
>     <Email>medogu~medogu</Email>

Ожидается:
- значение поля sender в зарегистрированной в БД записи соответствует значению из ini файла

Получено:
- значение поля соответствует настройкам агента мониторинга.

**Comment by ikudin** [comment]
в ini файле нет отправителя....

**Comment by oknoproblem** [comment]
да, этот момент я как-то упустил... согласен.
