### ISSUE TITLE
Не работает скрипт создания процедуры устаревания статусов сообщения.

### ISSUE THREAD

**Issue by oknoproblem** [oknoproblem/medo_agent#120]
скрипт создания 1_single_expireStatus.sql от 20160615 выполняется с ошибкой:
Msg 213, Level 16, State 1, Procedure single_expireStatus, Line 56
Имя столбца или число предоставленных значений не соответствует определению таблицы.

**Comment by ikudin** [comment]
Положи, пожалуйста, скрипт на фтп

**Comment by ikudin** [comment]
Который у тебя)

**Comment by oknoproblem** [comment]
положил (scripts.zip), все скрипты должны отрабатывать

там структура таблицы [MedoService.Backend].dbo.Requests изменилась сильно, тебе надо указывать в инсерте на 71ой строчке какие конкретно поля ты хочешь заполнить какими значениями, ну и не забудь на чистой базе прогнать для проверки, в том числе скрипты создания автостарта.

Как я говорил, для этой части нужна пошаговая инструкция.

**Comment by oknoproblem** [comment]
если что, я там подправил этот инсерт, но добиться генерации инцидентов по просроченным статусам так и не смог.

**Comment by ikudin** [comment]
Спасибо) По-моему не только она изменилась. проверю сегодня-завтра.пока нет возможности пригнать кого-нибудь к себе домой, чтобы комп включили)

**Comment by ikudin** [comment]
должно работать. положил скрипты

**Comment by oknoproblem** [comment]
не работает скрипт автостарта таймера

`exec sp_procoption loop_expireStatus, startup, true`

ошибка:

> Сообщение 15398, уровень 11, состояние 1, процедура sp_procoption, строка 73
> Измененные параметры запуска могут иметь только объекты в базе данных master, владельцем которых является dbo.

**Comment by oknoproblem** [comment]
Инциденды так же не создаются.

Могу дать доступ до стенда.

**Comment by ikudin** [comment]
скрипты исправил, положил. 
с инструкцией все очень весело - выполнить по порядку. если ранее выполнялись, то заменить CREATE на ALTER.
я могу слить все в один скрипт, если надо.
могу проверять на существование и удалять, если уже есть.
скажи, как сделать, я сделаю.

**Comment by ikudin** [comment]
Работает?

**Comment by oknoproblem** [comment]
да, только кушает много.
