### ISSUE TITLE
Настройки "Предельное время нахождение сообщения в статусе (мин)" возвращаются в "5 минут" при перезагрузке сервера/ISS

### ISSUE THREAD

**Issue by oknoproblem** [oknoproblem/medo_agent#122]
Настройки "Предельное время нахождение сообщения в статусе (мин)" возвращаются в "5 минут" при перезагрузке сервера/ISS

Так быть не должно. Настройки должны сохранять указанное значение.

**Comment by ikudin** [comment]
поправиил.вроде как работает)
