### ISSUE TITLE
Ошибка разбора уведомления "Ссылка на объект не указывает на экземпляр объекта. "

### ISSUE THREAD

**Issue by oknoproblem** [oknoproblem/medo_agent#123]
При разборе уведомления (на ФТП файл 111.zip) создаётся некорректный инцидент см скрин
![default](https://cloud.githubusercontent.com/assets/6616341/18549924/185fe918-7b5a-11e6-8777-6569ed122e75.PNG)

**Comment by oknoproblem** [comment]
скорее всего связано с попыткой создать связь с несуществующим документом.

**Comment by ikudin** [comment]
да нет, это в коде было. там просто в хмл нет атрибута id у эл-та notification.
а агент его сильно хотел. исправил
