### ISSUE TITLE
При регистрации инцидента с текстом "Ссылка на объект не указывает на экземпляр объекта." указывать ведомство, ане "Агент"

### ISSUE THREAD

**Issue by oknoproblem** [oknoproblem/medo_agent#124]
В качестве значения поля Податель некорректно указывать значение "Агент", данный инцидент будет невозможно урегулировать, так как данное сообщение никогда не будет найдено.

ВСЕГДА указывать в качестве подателя собственное ведомство агента, адрес и uid которого имеется в настройках агента.

![default](https://cloud.githubusercontent.com/assets/6616341/18550113/f97795cc-7b5a-11e6-94fa-3284f98bfc2c.PNG)

**Comment by ikudin** [comment]
это значение ставится в том случае, если подателя нет как такового.  а податель - это пользователь.
это обговаривалось в предыдущих замечаниях и багах.
как сделать? податель - это ведомство или пользователь?

**Comment by oknoproblem** [comment]
Предложи как сделать так, чтобы ВСЕГДА можно было понять, какое ведомство сгенерировало инцидент. Если говорить об инциденте на скриншоте, он был сгенерирован Администрацией Самарской области (на фтп 111.zip). Упоминания об этом нет вообще.

**Comment by ikudin** [comment]
Добавил ведомство на странице информации о заявке/инциденте. Ведомство - отправитель письма при инциденте или ведомство, которое указал пользователь при создании заявки
