### ISSUE TITLE
При большом кол-ве инцидентов/заявок/сообщений загрузка подвисает (Internal Server error 500)

### ISSUE THREAD

**Issue by oknoproblem** [oknoproblem/medo_agent#125]
см. скрин. Такое происходит не всегда, где-то надо увеличить таймаут.
![001](https://cloud.githubusercontent.com/assets/6616341/18551222/28b5d790-7b60-11e6-837e-f9e8e984d66e.png)

Могу дать доступ до моего стенда, у меня часто воспроизводится.

**Comment by ikudin** [comment]
тут дело не в таймауте, а в какой-то ошибке сервера в бэкенде...можешь свою базу скинуть? с кучей данных

**Comment by oknoproblem** [comment]
на фтп MedoService.Backend.bak

**Comment by ikudin** [comment]
не могу повторить ошибку. у себя увеличил ОЗУ до 4Гб, ибо забивалась.
скидываю все. если ошибка повторится, то скинь скрин, т.к. должно быть описание ошибки, по идее.

**Comment by ikudin** [comment]
все. победил))) некоторые запросы выполняются минуты по 2, но выполняются без ошибок;)
