### ISSUE TITLE
Как реализована обработка писем с ошибками?

### ISSUE THREAD

**Issue by oknoproblem** [oknoproblem/medo_agent#13]

**Comment by oknoproblem** [comment]
Вопрос вот в чём, на нашем клиентском приложении, папка с письмом лежит до момента попытки её отправки. И в случае если письмо содержит ошибки, оно перемещается в папку error. Не знаю как вы настраиваете на монопаках это. 

Потенциально письмо может пройти мимо обработки.

**Comment by ikudin** [comment]
в таком случае по таймауту статуса будет видно, что письмо получено от абонента (т.е. перемещено к нам монопаком), но не отправлено в течение получаса, к примеру. значит, что оно в ошибках. как-то так, наверно.
на любой статус можно мониторить неограниченное кол-во папок.

**Comment by oknoproblem** [comment]
Мы вообще это письмо можем не увидеть, так как клиент отправки может его обработать, положив в папку error, до того как агент мониторинга его увидит.

**Comment by oknoproblem** [comment]
обсудили по телефону, всё вроде понятно стало более менее.
