### ISSUE TITLE
Отсутствие необходимых реквизитов в списке сообщений

### ISSUE THREAD

**Issue by oknoproblem** [oknoproblem/medo_agent#139]
Отсутствие необходимых реквизитов в списке сообщений

после обновления и перезагрузки последней версии, пропали все реквизиты сообщений в списке:
![001](https://cloud.githubusercontent.com/assets/6616341/18947491/f120c5e2-863b-11e6-9f6d-cf4016dd5c87.png)

**Comment by ikudin** [comment]
починил

**Comment by oknoproblem** [comment]
ok
