### ISSUE TITLE
Реализовано ли требование, и если да то как?

### ISSUE THREAD

**Issue by oknoproblem** [oknoproblem/medo_agent#14]
> Для каждого статуса может устанавливаться время его существования. При нарушении установленного времени существования статуса должен автоматически фиксироваться инцидент.

В какой таблице задаётся время ожидания?

**Comment by ikudin** [comment]
в таблице ms_letters_statuses там поле ttl. дело в том, что работу по отслеживанию должен выполенять скрипт БД. так назыфваемый job или просто служба, которая будет выполнять запрос. запрос пришлю сегодня вечером/утром

**Comment by ikudin** [comment]
ну все готово, в общем-то.
по ссылке выложен бэкап БД. там много изменений, поэтому сразу все даю.
просмотреть письма, у которых время существования статуса истекло, можно в представлении status_expired. пока что думаю, как лучше сделать генерацию инцидентов, ведь при изменении статуса инцидент по старому статусу должен будет завкрываться, по идее. в общем, подумаю немного, а пока надо тестировать.
убрал дублирование писем,добавил генерацию инйцидентов по тем уведомлениям, у которых нет письма, на которые они пришли

**Comment by oknoproblem** [comment]
ok
