### ISSUE TITLE
Надо закрыть все, что исправлено

### ISSUE THREAD

**Issue by ikudin** [oknoproblem/medo_agent#15]
Я везде отписался,жду Андреевских ответов и тестирования последней версии.
из существенного осталось сделать 
1.поддержку транспортного контейнера 
2.скрипт по генерации и закрытию инцидентов по истечению времени для статусов. (он почти готов, но голова уже не варит)

это сделаю завтра. проснусь поздно, но все будет готово.

**Comment by oknoproblem** [comment]
Иван, я закрою, в данный моент занимаюсь разработкой ПиМИ, что более приоритетно. Как закончу, займусь вплотную тестированием.
