### ISSUE TITLE
Ошибка процедуры БД при обработке сообщения

### ISSUE THREAD

**Issue by oknoproblem** [oknoproblem/medo_agent#16]
System.Data.SqlClient.SqlException: Для процедуры или функции AddDocument указано слишком много аргументов.
   в System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection)
   в System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj)
   в System.Data.SqlClient.TdsParser.Run(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj)
   в System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString)
   в System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async)
   в System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, DbAsyncResult result)
   в System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(DbAsyncResult result, String methodName, Boolean sendToPipe)
   в System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   в AgentService.Helpers.Agent.ProcessFolder(Folder folder) в e:\OneDrive\VisualStudio\Projects\AgentService_svn\AgentService\Helpers\Agent.cs:строка 222

**Comment by oknoproblem** [comment]
так же, необходимо убрать лишние файлы из папки SQLInit. Я не понимаю уже как мне разворачивать БД.

**Comment by ikudin** [comment]
Бд разворачивать не нужно! Есть бэкап базы, который лежит в корне по ссылке! 
Поэтому возникают ошибки!

**Comment by ikudin** [comment]
Процесс разворачивания бэкапа в бд можно найти в интернете ;)

**Comment by oknoproblem** [comment]
Иван, накатить скрипт на созданную БД я могу, у нас в данный момент минимум 3 скрипта в папке SQLInit отвечающих за таблицы, будьте добры, либо написать инструкцию который использовать, либо оставить в папке только тот который актуальный.

**Comment by ikudin** [comment]
В данный момент дать скрипт не могу. Поэтому предлагаю развернуть готовую из бэкапа. Можно просто нажать правой кнопкой на базу и нажать восстановить. Выбрать файл с бэкапом

**Comment by oknoproblem** [comment]
я это пробовал с фалом Second.sql и с файлом Tables.sql.

оба скрипта приводят к ошибке из первого комментария при добавлении Документа.

**Comment by oknoproblem** [comment]
я понял в чём проблема, вы в данный момент предлагаете востанавливать БД из файла db.bak из корня проекта. Надо было мне об этом минимум сообщить. Я не телепат... .

Данный способ работает только на 2012 MSSQL, у меня в распоряжении 2008...

> Заданное приведение является недопустимым. (SqlManagerUI)

при попытке использовать данный bak файл.

**Comment by ikudin** [comment]
Вот это плохо... Вообще нет новее?

**Comment by ikudin** [comment]
Прошу прощения, что не уточнил

**Comment by oknoproblem** [comment]
что-нибудь придумаем.

**Comment by oknoproblem** [comment]
подняли 2012, ошибка не воспроизводится на корректном файле бэкапа.
