### ISSUE TITLE
Проблема отслеживания писем с ошибками в структуре конверта

### ISSUE THREAD

**Issue by oknoproblem** [oknoproblem/medo_agent#17]
Иван, при попытке переслать сообщение с отсутствующих/невалидным файлом конверта, клиент отправки переложит его в папку Error.

Я правильно понимаю, что письма со статусом Получено предлагается отслеживать в двух папках? Или это как-то по другому реализовано?

Иначе мы никогда не узнаем что поступило письмо с ошибкой в конверте.

**Comment by ikudin** [comment]
Я в таком случае предлагаю добавить статус "ошибка при отправке". Это первое, что приходит в голову

**Comment by ikudin** [comment]
сейчас еще раз перечитал. думаю, что ваш вариант будет правильнее.
то есть отслеживаем в двух папках, просто в результате по тем письмам, которые попали в папку ошибочных, будет сгенерирован инцидент

**Comment by ikudin** [comment]
и в будущем по таймауту статуса будет сгенерирован инцидент

**Comment by oknoproblem** [comment]
ок, закрываю.
