### ISSUE TITLE
Вопрос по типам инцидентов

### ISSUE THREAD

**Issue by oknoproblem** [oknoproblem/medo_agent#18]
Иван, следующие типы инцидентов:
1.	Невозможно получить письма от субъекта
2.	Невозможно отправить письма 
3.	Невозможно получить письма
4.	Невозможно отправить письмо субъекту
5.	Не получена квитанция от субъекта
6.	Невозможно отправить квитанцию 
7.	Невозможно получить квитанцию 
8.	Невозможно отправить квитанцию субъекту
9.	Не получено уведомление от субъекта
10.	Невозможно отправить уведомление
11.	Невозможно получить уведомление
12.	Невозможно отправить уведомление субъекту

Мне нужно чёткое понимание как каждый из этих инцидентов получить.

**Comment by ikudin** [comment]
Понял свою ошибку. Исправлю 20го числа. В зависимости от типа письма и его просроченного статуса буду ставить один из перечисленныз статусов.

**Comment by oknoproblem** [comment]
Иван, очень жду реализации данного функционала или описания как оно будет реализовано для каждого статуса. Мне необходимо добавить это в ПиМИ

**Comment by ikudin** [comment]
функционал готов (реалитзован в БД в процедуре ProcessExpires), кроме следующих статусов:
1. Невозможно получить письма от субъекта
5. Не получена квитанция от субъекта
9. Не получено уведомление от субъекта

1 - Это должно будет реализовано через подключение к сетевым папкам объекта. Сделаю сегодня, максимум - завтра.
5 и 9 - мне нужно знать, когда генерировать эти инциденты. Ведь не все ведомства отправляют уведомления и квитанции. Да и уведомления могут быть разными.

**Comment by ikudin** [comment]
ах да, надо бэкап базы новый взять, чтобы этот функционал был)

**Comment by ikudin** [comment]
1 сделал.
Изменился файл настроек, БД и само приложение. так что  лучше все перекачать.
в настройках добавились пункты для подклоючения к папке сетевой.

Осталось только 5 и 9. Мое предложение - объединить эти три инцидента в один, так как, если подключения не будет, то невозможно будет получить ни письмо, ни квитанцию, ни уведомление.

**Comment by oknoproblem** [comment]
А в какой таблице задаётся таймаут для инцидента?

я правильно понимаю, что реализован один тип инцидента с разными текстовыми описаниями (судя по коду процедуры)? 
Т.е. возможности задать разное время таймаутов для разных "инцидентов" не будет?

**Comment by ikudin** [comment]
решено?

**Comment by oknoproblem** [comment]
пока да, не закрываю так как ещё не все варианты проверил.

**Comment by oknoproblem** [comment]
> 5. Не получена квитанция от субъекта
> 6. Невозможно отправить квитанцию 
> 7. Невозможно получить квитанцию 
> 8. Невозможно отправить квитанцию субъекту
> 9. Не получено уведомление от субъекта
> 10. Невозможно отправить уведомление
> 11. Невозможно получить уведомление
> 12. Невозможно отправить уведомление субъекту

каким образом отслеживаются данные инциденты?

**Comment by oknoproblem** [comment]
если не сложно, то по телефону.

**Comment by oknoproblem** [comment]
Для того чтобы сдать этап работ, необходимо сделать статусы как в ТЗ, т.е. отдельно определяем какой тип сообщения прежде чем регистрируем инцидент и текс соответственно должен быть как в ТЗ.

**Comment by oknoproblem** [comment]
ок
