### ISSUE TITLE
Не проверяется наличие файлов перечисленных в файле контейнере если нарушена нумерация 

### ISSUE THREAD

**Issue by oknoproblem** [oknoproblem/medo_agent#20]
шаги: 
- в папку положить сообщение у которого в файле конверте описаны вложения отсутствующие в папке сообщения

Ожидается:
- при обработке сообщения зарегистрируется инцидент "Ошибка при разборе письма"
- Письмо должно быть зарегистрировано при возможности

Получено:
- сообщение зарегистрировано
- инцидент присутствует НО не привязан к сообщению

**Comment by ikudin** [comment]
Какой инцидент генерировать при нарушении нумерации? Исправлю 20 числа

**Comment by oknoproblem** [comment]
никакой, это не критическая ошибка, если все файлы на месте, инцидент не стоит генерировать. Так работает клиент отправки, он игнорирует нумерацию и в случае если письмо корректное отправляет его. 
Эту доработку Андрей с нас заказывал и она реализована.

**Comment by ikudin** [comment]
если есть ошибка в нумерации адресатов или файлов в настоящее время генерируется инцидент о том, что нумерация нарушена, но инфа о письме пишется в БД, то есть письмо пускается дальше. так нормально?

**Comment by oknoproblem** [comment]
Да, в принципе ок, повод попинать министерство что они допускают ошибки при генерации ini.

**Comment by ikudin** [comment]
хорошо, тогда проверьте и закроем)

**Comment by oknoproblem** [comment]
ok
