### ISSUE TITLE
Зачем в новой версии блок share в конфиге? 

### ISSUE THREAD

**Issue by oknoproblem** [oknoproblem/medo_agent#21]
Зачем в новой версии блок share в конфиге? 

через сетевые диски работать нельзя? Зачем заводить лишнюю сущность?

**Comment by ikudin** [comment]
Этот блок нужен для того, чтобы агент периодически подключался к сетевой папке на стороне ведомства. Если подключиться невозможно, то создается инцидент типа "невозможно получить письмо". 
В связи с этим я предлагал объединить инциденты

**Comment by oknoproblem** [comment]
почему нельзя просто как в случае с обычными папками использовать folders?
если папка доступна, то всё ок, если папка не доступна, то делаем инцидент, но вообще нам нет необходимости проверять папку, так как инцидент создастся при таймауте в предыдущем статусе письма.

**Comment by ikudin** [comment]
не создастся, так как мы не можем получать письма. (то есть это письмо никогда не появится).
этот блок появился после последнего письма андрея

**Comment by oknoproblem** [comment]
нет, нам не нужен отдельный блок, статус создасться, так как письма из папки полученно клиента отправки не переместятся в сетевую папку ведомства и соответственно будет инцидент по таймауту для документа.

можем созвониться обсудить чтобы быстрее было.

**Comment by ikudin** [comment]
решено?

**Comment by oknoproblem** [comment]
да
