### ISSUE TITLE
ошибка при запуске службы

### ISSUE THREAD

**Issue by oknoproblem** [oknoproblem/medo_agent#22]
Контейнер ошибки , тип 0
Имя события: CLR20r3
Ответ: Нет данных
Идентификатор CAB: 0

Сигнатура проблемы:
P1: agentservice.exe
P2: 1.0.0.0
P3: 56c854ba
P4: AgentService
P5: 1.0.0.0
P6: 56c854ba
P7: 18
P8: 211
P9: System.NullReferenceException
P10: 

Вложенные файлы:
Эти файлы можно найти здесь:
C:\ProgramData\Microsoft\Windows\WER\ReportQueue\AppCrash_agentservice.exe_2b4219a839724e7d411be278732d7df375b0ed_92fb3840

Символ анализа: 
Повторный поиск решения: 0
Идентификатор отчета: 4472b816-dac4-11e5-992b-3085a99bb582

**Comment by oknoproblem** [comment]
очень жду исправления

**Comment by ikudin** [comment]
сейчас посмотрю, это странно

**Comment by ikudin** [comment]
у меня все работает...попробуйте перекачать exe службы

**Comment by oknoproblem** [comment]
перекачать файл не помогает.

**Comment by oknoproblem** [comment]
использую данный файл

> AgentService\bin\Debug

**Comment by ikudin** [comment]
еще одно решение. попробуйте сменить пользователя, от которого запускается служба. есть несколько системных записей. если от них не получится, запускайте от админа

**Comment by ikudin** [comment]
есть контакт?

**Comment by oknoproblem** [comment]
нет, не работает

могу выслать дампы если надо.

**Comment by ikudin** [comment]
запустите в режиме консоли, как обычное приложение
что выдает? есть teamviewer?

**Comment by oknoproblem** [comment]
отправил контакты на почту

**Comment by ikudin** [comment]
решено?

**Comment by oknoproblem** [comment]
да
