### ISSUE TITLE
у статуса Доставлено, не должно быть времени жизни.

### ISSUE THREAD

**Issue by oknoproblem** [oknoproblem/medo_agent#23]
у статуса Доставлено, не должно быть времени жизни, 

и надо предусмотреть возможность указать бесконечность для всех статусов (если ещё не предусмотрено).

типа если указано 0 то инциденты не создавать.

**Comment by ikudin** [comment]
так и сделаем. если 0 - то не создаем, а у доставлено по умолчанию 0 будет просто.
сделаю, отпишусь

**Comment by oknoproblem** [comment]
ok
