### ISSUE TITLE
Переезд на закрытую джиру

### ISSUE THREAD

**Issue by oknoproblem** [oknoproblem/medo_agent#24]
Иван, в связи с особенностями конкурса, с завтрышнего дня работаем не тут, а в закрытой Джире:

https://212.74.241.86:47359/projects/PORT/issues/PORT-2?filter=allissues

ссылку на регистрацию я вам присылал в пятницу на почту (могу повторить при необходимости)

по любым вопросам, готов ответить.

**Comment by oknoproblem** [comment]
через пару дней данный проект удалю.

**Comment by ikudin** [comment]
принято

**Comment by oknoproblem** [comment]
пока отменяется....

**Comment by oknoproblem** [comment]
закрою чтобы не мешала
