### ISSUE TITLE
Сводка: не корректное кол-во заявок/инцидентов в соответствующих фильтрах

### ISSUE THREAD

**Issue by oknoproblem** [oknoproblem/medo_agent#25]
В фильтрах:
Новых (незакрытых) заявок
Новых (неустранённых) инцидентов  - (кстати слово "не устранённых" пишется раздельно.)

одинаковое число в кружочках

**Comment by ikudin** [comment]
кстати, слитно. Слитно (с приставкой не-) пишутся прилагательные, называющие признак. Их почти всегда можно заменить синонимами без не: Этот дом небольшой (маленький). Взгляд был несмелым (робким).
это можно объединить с некорректным составом атрибутов

**Comment by oknoproblem** [comment]
ок, да, согласен, ворд и браузер меня ввели в заблуждение.

**Comment by oknoproblem** [comment]
ок
