### ISSUE TITLE
Кнопка BACKSPACE

### ISSUE THREAD

**Issue by oknoproblem** [oknoproblem/medo_agent#27]
При нажатии кнопки, происходит переход между вкладками приложения...

**Comment by ikudin** [comment]
это браузер так работает, а не приложение. В браузере при нажатии backspace происходит переход назад. а combobox - это не поле ввода, он там и не должен работать

**Comment by ikudin** [comment]
но я все же сделаю поле ввода, уже в процессе

**Comment by oknoproblem** [comment]
в браузере при перемещении фокуса на текстовое поле, бэкспэйс работает на стирание, в приложении нет.

Общее правило, если в поле можно ввести текст, его должно быть возможно удалить через backspace

**Comment by ikudin** [comment]
так в текстовых полях все работает. Андрей жал на бэкспейс в комбобоксе

**Comment by oknoproblem** [comment]
выбор ведомства это у нас комбобокс? если да то в комбобоксах не должен работать бэкспэйс

**Comment by ikudin** [comment]
бэкспейс работает в браузере, а не в приложении) но я сделал, как просили, увидишь

**Comment by oknoproblem** [comment]
ок
