### ISSUE TITLE
Сводка: выравнивание атрибутов в карточках фильтров

### ISSUE THREAD

**Issue by oknoproblem** [oknoproblem/medo_agent#29]
Во всех 4х фильтрах вкладки Сводка совершенно нет никакого выравнивания на строках.
![001](https://cloud.githubusercontent.com/assets/6616341/15358192/b9628a9e-1d0b-11e6-9a35-09098967fe8e.png)

Так не пойдёт, необходимо выравнивание во всех блоках согласно атрибутивному составу.

**Comment by ikudin** [comment]
будет тот состав атрибутов, который есть на вкладках сообщения и заявки

**Comment by oknoproblem** [comment]
что? не в тот дефек пишешь?

**Comment by ikudin** [comment]
да нет, в тот. выравнивание от состава зависит)

**Comment by oknoproblem** [comment]
так в этом и ошибка, выравнивание не должно зависеть от контента...

**Comment by ikudin** [comment]
мне задать жесткие размеры каждого поля?

**Comment by oknoproblem** [comment]
ну да, такого как сейчас разброса быть не должно, интерфейс не должен представлять из себя кашу.

**Comment by oknoproblem** [comment]
Всё ещё актуально. 
Выравнивание должно быть, без разницы какие размеры ты поставишь, главное чтобы везде одинаковые элементы одинаково отображались.

**Comment by ikudin** [comment]
проверь, вроде нормально все

**Comment by oknoproblem** [comment]
ok
