### ISSUE TITLE
При создании инцидентов по документам по которым возможно достать номер документа его необходимо доставать, так же как и сам документ необходимо регистрировать

### ISSUE THREAD

**Issue by oknoproblem** [oknoproblem/medo_agent#30]
При создании инцидентов по документам по которым возможно достать номер документа его необходимо доставать, так же как и сам документ необходимо регистрировать.

В данный момент как минимум инциденты с разбором xml фалов не имеют ссылки на документы.

**Comment by ikudin** [comment]
инцидент создается по сообщению, а не документу...
или имеется в виду, что если ссылка ведет на документ, то доставать номер документа?

**Comment by oknoproblem** [comment]
![001](https://cloud.githubusercontent.com/assets/6616341/15389213/6dce57bc-1dbe-11e6-800f-bba8c8dbe840.png)

**Comment by oknoproblem** [comment]
мы уже обсуждали данную проблему в предыдущей реализации агента мониторинга. Сообщение должно быть зарегистрировано если у агента достаточно для этого данных.
На атрибутивный состав Инцидентов будет отдельная бага.

**Comment by ikudin** [comment]
с утра завтра-ночью дам новую версию с исправленными недостатками и составом атрибутов.
скрины в доки придется тоже завтра с утра ставить

**Comment by ikudin** [comment]
в новой версии агента работает
