### ISSUE TITLE
Сообщения: не отображается статус сообщения в МЭДО/СЭД, даже если он есть у документа

### ISSUE THREAD

**Issue by oknoproblem** [oknoproblem/medo_agent#32]
![001](https://cloud.githubusercontent.com/assets/6616341/15419593/c041a696-1e6f-11e6-8ec1-de118486a447.png)

Не заполняются  атрибуты карточки сообщения Статус в МЭДО/СЭД.

**Comment by ikudin** [comment]
отображается, проверяли же?

**Comment by oknoproblem** [comment]
да нет же, я же скрин спецом приложил.

![001](https://cloud.githubusercontent.com/assets/6616341/15461414/6b6756a6-20c3-11e6-8581-f373bcc3acba.png)

**Comment by ikudin** [comment]
а какой статус сэд там брать? логически их не выстроишь, по времени?

**Comment by oknoproblem** [comment]
да, мы это вроде обсуждали. берём по времени. Это вообще странный атрибут для системы МЭДО, но в ТЗ он есть, берём как проще всего.

**Comment by ikudin** [comment]
я когда начал вникать мне половина атрибутов, которые мы вытаскиваем, показались весьма странными. но что не сделаешь ради любимой системы

**Comment by oknoproblem** [comment]
Статус СЭД теперь отображается, остался "статус МЭДО" на карточке объекта, смотри скрин со стрелками.

**Comment by oknoproblem** [comment]
ok
