### ISSUE TITLE
Не заполняется поле Аннотация на карточке документа, хотя она присутствует в xml файле

### ISSUE THREAD

**Issue by oknoproblem** [oknoproblem/medo_agent#33]
Не заполняется поле Аннотация на карточке документа, хотя она присутствует в xml файле

см. файл 
good_document_68B2871F-BC0A-451B-0000-000000000017.zip

на фтп.

**Comment by ikudin** [comment]
а это потому что она никогда оттуда и не бралась.

**Comment by oknoproblem** [comment]
И? Так может стоит брать её от туда? Что за комментарий, Иван, отвечай развёрнуто.

**Comment by ikudin** [comment]
сделал, версию выложу чуть позже

**Comment by oknoproblem** [comment]
Всё ещё нет аннотации.

**Comment by oknoproblem** [comment]
ок
