### ISSUE TITLE
Сообщения/фильтр сообщений: при нажатии кнопки Enter на клавиатуре, применять параметры фильтра

### ISSUE THREAD

**Issue by oknoproblem** [oknoproblem/medo_agent#34]
при нажатии кнопки Enter на клавиатуре, должна нажиматься кнопка "Найти" фильтра.
![001](https://cloud.githubusercontent.com/assets/6616341/15420016/cfb672fc-1e72-11e6-8bef-3ba1095e3c88.png)

**Comment by ikudin** [comment]
работает

**Comment by oknoproblem** [comment]
ок
