### ISSUE TITLE
Сообщения: при отображении результатов поиска не выбирается первый в списке элемент

### ISSUE THREAD

**Issue by oknoproblem** [oknoproblem/medo_agent#38]
при отображении результатов поиска не выбирается первый в списке элемент
![001](https://cloud.githubusercontent.com/assets/6616341/15420990/d38972c4-1e79-11e6-9c01-1d95ed7add63.png)

раньше выбиралось, было круто.

**Comment by ikudin** [comment]
готово

**Comment by oknoproblem** [comment]
ок
