### ISSUE TITLE
Сообщения: у уведомлений не корректная дата создания

### ISSUE THREAD

**Issue by oknoproblem** [oknoproblem/medo_agent#39]
при регистрации уведомления агент шлёт не корректную дату регистрации уведомления, должна быть текущая, а берётся из xml

**Comment by oknoproblem** [comment]
та же ерунда для документов.

**Comment by oknoproblem** [comment]
Добавлю скрин про даты на документе:
![001](https://cloud.githubusercontent.com/assets/6616341/15426683/99b01a98-1e98-11e6-96a9-1dee265cf1fe.png)
Согласно Прототипу должно быть так.

**Comment by ikudin** [comment]
вроде так и есть

**Comment by oknoproblem** [comment]
дата создания сообщения должна быть текущей, а не браться из xml

**Comment by oknoproblem** [comment]
ok
