### ISSUE TITLE
Сообщения фильтр: Фильтр сообщений по ведомствам работает не корректно

### ISSUE THREAD

**Issue by oknoproblem** [oknoproblem/medo_agent#40]
При выборе значения test_2~MEDOGU
получил сообщения от трёх ведомств
test
test_2~MEDOGU
test_2@MEDOGU
![001](https://cloud.githubusercontent.com/assets/6616341/15422735/9582d426-1e82-11e6-920c-c6cb6d8fb49f.png)

Такого определённо быть не должно

**Comment by ikudin** [comment]
у меня все работает, проверь у себя еще раз с новой версией

**Comment by oknoproblem** [comment]
ок
