### ISSUE TITLE
Сообщения, отсусттвует регистрация повтора для сообщений

### ISSUE THREAD

**Issue by oknoproblem** [oknoproblem/medo_agent#41]
При повторной отправки сообщения через агент отсутствует регистрация Повтора отправки, см. скрин.

![001](https://cloud.githubusercontent.com/assets/6616341/15423064/523af37c-1e84-11e6-887c-0c7cc8a3d3bf.png)

Вместо этого регистрируется повторно только статус.

**Comment by ikudin** [comment]
должно работать теперь
