### ISSUE TITLE
Отсутствуют шрифты при загрузки страницы приложения

### ISSUE THREAD

**Issue by oknoproblem** [oknoproblem/medo_agent#42]
При загрузке страницы 
http://10.1.136.185/fonts/fontawesome-webfont.woff?v=4.5.0
http://10.1.136.185/fonts/glyphicons-halflings-regular.woff

Подгрузить их пытается jquery-2.2.1.min.js

![001](https://cloud.githubusercontent.com/assets/6616341/15426336/8a3cc176-1e96-11e6-8188-394821ba983e.png)

**Comment by ikudin** [comment]
удалил

**Comment by oknoproblem** [comment]
что-то как-то нет:
![001](https://cloud.githubusercontent.com/assets/6616341/15606873/8d79dc6c-2417-11e6-8db0-689dbe1cd6ad.png)

**Comment by ikudin** [comment]
у меня такого нет..

**Comment by oknoproblem** [comment]
Ну можешь зайти у нас посмотреть...

**Comment by ikudin** [comment]
хрен его знает, у меня почему-то не всегда проявляяется. разберусь по ходу

**Comment by oknoproblem** [comment]
для нашего стенда всё ещё актуально.

**Comment by ikudin** [comment]
http://stackoverflow.com/questions/4015816/why-is-font-face-throwing-a-404-error-on-woff-files
решение проблемы.
это надо будет сделать на веб сервере. у нас я сам сделаю.

**Comment by oknoproblem** [comment]
ок
