### ISSUE TITLE
"Номер документа" == "№ документа" в списке сообщений

### ISSUE THREAD

**Issue by oknoproblem** [oknoproblem/medo_agent#43]
Переименовать "Номер документа" в "№ документа" в списке сообщений, это позволит писать имя атрибута в одну строку...

![001](https://cloud.githubusercontent.com/assets/6616341/15426482/a3ecdb14-1e97-11e6-9032-88fd7c4a5a1b.png)

**Comment by ikudin** [comment]
готово

**Comment by oknoproblem** [comment]
На карточке докмента тоже должен быть через № смотри первый скрин, там две стрелки.

**Comment by oknoproblem** [comment]
В дополнение, данный атрибут на вкладке Сводка у всех элементов также должен быть через №

**Comment by ikudin** [comment]
исправлено

**Comment by oknoproblem** [comment]
остались карточки Заявок и инцидентов:
![001](https://cloud.githubusercontent.com/assets/6616341/15606821/3c85eb20-2417-11e6-88d5-60f2d31366ec.png)

**Comment by ikudin** [comment]
есть

**Comment by oknoproblem** [comment]
ок
