### ISSUE TITLE
Не генерируются инциденты по просрочке статусов

### ISSUE THREAD

**Issue by oknoproblem** [oknoproblem/medo_agent#45]
Не генерируются инциденты по просрочке статусов

**Comment by oknoproblem** [comment]
очень жду исправления по данной ошибке.

**Comment by ikudin** [comment]
я отписался, будет процедура в бд, на программу не повлияет. сегодня будет

**Comment by oknoproblem** [comment]
потенциально работает, буду подробнее проверять.
