### ISSUE TITLE
Не работает добавление пользователей (думаю что спрапвочник ведомств съехал)

### ISSUE THREAD

**Issue by oknoproblem** [oknoproblem/medo_agent#49]
Не работает добавление пользователей (думаю, что справочник ведомств съехал)

при нажатии на кнопку Добавить при корректно заполненных полях ничего не происходит.

**Comment by ikudin** [comment]
все норм, посмотри

**Comment by oknoproblem** [comment]
не помогло, новогго пользователя создать нельзя.

**Comment by ikudin** [comment]
не знаю, у меня все работает) имя напиши на англ

**Comment by oknoproblem** [comment]
ok
