### ISSUE TITLE
Не регистрируется Документ в случае наличия ошибки в файле ini

### ISSUE THREAD

**Issue by oknoproblem** [oknoproblem/medo_agent#5]
Шаги:
- в папку отправленные положить документ в файле конверте (ini файл) которого указаны файлы отсутствующие в папке
- запустить обработку папки отправленные агентом

Ожидается:
- документ должен регистрироваться в БД в любом случае кроме случаев отсутствия ini файла или не читаемого ini файла.

Получено:
- документ не регистрируется в БД, создаётся только инцидент.

**Comment by oknoproblem** [comment]
я думаю регистрация документа если информации для этого достаточно необходима.

**Comment by ikudin** [comment]
Исправил, прошу простестировать.

**Comment by oknoproblem** [comment]
создался инцидент типа 5 "В экземпляре объекта не задана ссылка на объект."
Текст description не однозначный.

**Comment by ikudin** [comment]
исправлено

**Comment by oknoproblem** [comment]
Инцидент невалидности xml файла описания не должен препятствовать регистрации сообщения.

шаги:
- отправить любое сообщение типа "документ" с корректным ini файлом.

Ожидается:
- в случае не соответствия файла описания xml схеме xsd сообщение всё равно должно регистрироваться в системе.

Получено:
- регистрируется только инцидент. Таблица [medo_service].[dbo].[ms_letters] пуста.

**Comment by oknoproblem** [comment]
Проблема с регистрацией сообщения типа "документ" при отсутствии не структурного файла вложения указанного в Ini файле так же осталась. 

На данный момент я не могу получить ни одного документа в БД.

**Comment by ikudin** [comment]
Исправлено

**Comment by oknoproblem** [comment]
Исправлено
