### ISSUE TITLE
Справочник ведомств сломан

### ISSUE THREAD

**Issue by oknoproblem** [oknoproblem/medo_agent#50]
Справочник ведомств сломан, см. скрин

![001](https://cloud.githubusercontent.com/assets/6616341/15468922/aaca71c6-20ef-11e6-816d-1afde8d908a7.png)

**Comment by ikudin** [comment]
все работает, версию положил

**Comment by oknoproblem** [comment]
ok

**Comment by ikudin** [comment]
буду закрывать все, что посчитаю исправленным, иначе начинаю путаться)
