### ISSUE TITLE
Фильтр сообщений: отсутствует возможность фильтрации по GUID сообщения

### ISSUE THREAD

**Issue by oknoproblem** [oknoproblem/medo_agent#52]
Согласно ТЗ должна быть возможность фильтрации по "Индентификатору сообщения"

Нужно, чтобы поле "Номер документа" в поиске сообщений позволяло искать как по регистрационному номеру документа, так и по GUID сообщения

**Comment by ikudin** [comment]
исправил

**Comment by oknoproblem** [comment]
Поиск проходит, но результаты очень странные, см. скрин
![001](https://cloud.githubusercontent.com/assets/6616341/15606611/ef9f9406-2415-11e6-974d-2e15cbd49751.png)

**Comment by ikudin** [comment]
а ты точно нажал найти?)) можешь дать тeam viewer, я посмотрю

**Comment by oknoproblem** [comment]
да я нажимал, и не раз... не воспроизводится
