### ISSUE TITLE
Поиск уведомлений должен так же происходить по номеру документа.

### ISSUE THREAD

**Issue by oknoproblem** [oknoproblem/medo_agent#53]
При поиске сообщений по номеру документа в список результатов должны попадать все уведомления проходившие через МЭДО, если у документа они присуствуют.

см. скрин.
![001](https://cloud.githubusercontent.com/assets/6616341/15505425/32190f3e-21cc-11e6-9a67-8f36e2c90e52.png)

**Comment by ikudin** [comment]
по идее должно работать. надо проверить

**Comment by oknoproblem** [comment]
поиск уведомлений по номеру документа происходит только в случае если в фильтре не выбрано "отображать сообщения типа документ", в случае если выбраны и Документ и Уведомление, отображается только документ

**Comment by ikudin** [comment]
попробуй квитанции отметить

**Comment by oknoproblem** [comment]
квитанции не причём, если выбрать только Документ и Уведомления, то показывается только документ, если снять Документ, то показываются уведомления.

**Comment by ikudin** [comment]
сделал

**Comment by ikudin** [comment]
а у меня все работает.

**Comment by oknoproblem** [comment]
поиск уведомлений по номеру документа всё ещё не работает.

**Comment by ikudin** [comment]
![2016-06-13](https://cloud.githubusercontent.com/assets/13745174/15997194/cfcef3de-3139-11e6-8cdb-da892bf76d46.png)

**Comment by ikudin** [comment]
просто ты когда-то просил включить поиск по гуидам в поиск по номеру документа. поэтому он может показывать больше. могу убрать, конечно
![Uploading 2016-06-13 (1).png…]()

**Comment by ikudin** [comment]
просто ты когда-то просил включить поиск по гуидам в поиск по номеру документа. поэтому он может показывать больше. могу убрать, конечно
![2016-06-13 1](https://cloud.githubusercontent.com/assets/13745174/15997302/0f883fa2-313b-11e6-8b93-4c594bf0d669.png)

**Comment by oknoproblem** [comment]
у меня не ищется ни по № документа ни по ГУИДу, должно и по тому и по другому искаться:
![001](https://cloud.githubusercontent.com/assets/6616341/16034916/fde82a72-321c-11e6-9346-50c9affe6606.png)

**Comment by ikudin** [comment]
подожди. есть гуид документа и есть гуид сообщения. по какому искать? и еще покажи мне само это уведомление

**Comment by oknoproblem** [comment]
да у уведомления почему-то не заполнены реквизиты документа:
![001](https://cloud.githubusercontent.com/assets/6616341/16036907/abace400-3226-11e6-8422-ba84788fd2f8.png)

**Comment by ikudin** [comment]
заполни номер, все будет работать

**Comment by ikudin** [comment]
номер в хмл

**Comment by oknoproblem** [comment]
`<?xml version="1.0" encoding="windows-1251"?>
<xdms:communication xdms:version="2.2" xmlns:xdms="http://www.infpres.com/IEDMS" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<xdms:header xdms:type="Уведомление" xdms:uid="67B1A44C-957F-4E64-A82D-000000000802" xdms:created="2016-03-02T15:45:01">
		<xdms:source xdms:uid="a2cc06ba-a4a2-4d9c-88f9-000000000002">
			<xdms:organization>Федеральное Казначейство</xdms:organization>
		</xdms:source>
	</xdms:header>
	<xdms:notification xdms:type="Назначен исполнитель" xdms:uid="b63ac5c2-e018-4201-bedb-bf1cc98a38f9" xdms:id="bf5662c8-70e2-427e-ba4d-000000000802">
		<xdms:documentAccepted>
			<xdms:time>2016-05-23T10:44:24</xdms:time>
			<xdms:foundation>
				<xdms:organization>Минкомсвязь</xdms:organization>
				<xdms:person>Алхазов Дмитрий Михайлович</xdms:person>
				<xdms:num>
					<xdms:number>27-2</xdms:number>
					<xdms:date>2016-05-29</xdms:date>
				</xdms:num>
			</xdms:foundation>
			<xdms:num>
				<xdms:number>39959-Вх</xdms:number>
				<xdms:date>2016-05-29</xdms:date>
			</xdms:num>
		</xdms:documentAccepted>
	</xdms:notification>
</xdms:communication>
`

**Comment by oknoproblem** [comment]
как видишь номер заполнен

**Comment by oknoproblem** [comment]
Номер документа всё ещё не заполняется при негистрации уведомления, хоть он и указан в xml

**Comment by oknoproblem** [comment]
![001](https://cloud.githubusercontent.com/assets/6616341/17134982/0164a09c-5336-11e6-85a1-2d5bd3c3712b.png)

**Comment by oknoproblem** [comment]
ок, забыл обновить агента
