### ISSUE TITLE
Не работает выгрузка результатов поиска Сообщений и Заявок/инцидентов.

### ISSUE THREAD

**Issue by oknoproblem** [oknoproblem/medo_agent#54]
При нажатии на кнопку XLS внизу списка Сообщений/заявок(инцидентов) ничего не происходит.

**Comment by ikudin** [comment]
Сделал для документов.

**Comment by oknoproblem** [comment]
надо какой-нибудь прогрессбар чтобы было видно что процесс идёт, иначе будет множество нажатий на кнопку и перегрузка интерфейса

**Comment by ikudin** [comment]
должно рботать

**Comment by oknoproblem** [comment]
ок, я так понимаю прогрессбар в виде неактивной кнопки, в принципе норм.
