### ISSUE TITLE
Невозможно создать новую заявку по кнопке "Создать заявку"

### ISSUE THREAD

**Issue by oknoproblem** [oknoproblem/medo_agent#55]
Невозможно создать новую заявку по кнопке "Создать заявку"

Нет реакции на нажатие кнопки "Добавить" при корректно заполненных полях.

**Comment by ikudin** [comment]
исправил.

**Comment by oknoproblem** [comment]
Невозможно выбрать тип создаваемой заявки, дропдаун пустой.

![001](https://cloud.githubusercontent.com/assets/6616341/15606370/7b0a5c08-2414-11e6-9440-6aa7e27bc44c.png)

**Comment by ikudin** [comment]
закрываю, создание завки по документу - уже есть баг
