### ISSUE TITLE
Сводка: json  в Новых незакрытых заявках

### ISSUE THREAD

**Issue by oknoproblem** [oknoproblem/medo_agent#56]
Сводка: json  в Новых незакрытых заявках

![001](https://cloud.githubusercontent.com/assets/6616341/15606779/fb16d082-2416-11e6-84c6-78bb5e97bcb7.png)

**Comment by ikudin** [comment]
извини))))оставил, блин)))

**Comment by ikudin** [comment]
испрвил

**Comment by oknoproblem** [comment]
ок
