### ISSUE TITLE
Не работает регистрация сообщений/инцидентов на агенте от 13ого числа.

### ISSUE THREAD

**Issue by oknoproblem** [oknoproblem/medo_agent#57]
Не работает регистрация сообщений/инцидентов на агенте от 13ого числа.

**Comment by ikudin** [comment]
проверь настройки агента, там все верно? я для тестирования менял на localhost

**Comment by ikudin** [comment]
положил версию агента, проверь ее

**Comment by oknoproblem** [comment]
закрываю
