### ISSUE TITLE
Сразу после создания заявки в списке заявок отображает две копии только созданной заявки

### ISSUE THREAD

**Issue by oknoproblem** [oknoproblem/medo_agent#61]
Сразу после создания заявки в списке заявок отображает две копии только созданной заявки
![001](https://cloud.githubusercontent.com/assets/6616341/15739099/22ba9e6c-28b7-11e6-99e6-433b23e56a91.png)

**Comment by ikudin** [comment]
ага, тоже заметил. а потом, если найти сразу нажать, то одна почему-то=)

**Comment by oknoproblem** [comment]
ok
