### ISSUE TITLE
В случае невозможности регистрации документа у инцидента ВСЕГДА должен быть проставлен отправитель/получатель

### ISSUE THREAD

**Issue by oknoproblem** [oknoproblem/medo_agent#62]
В случае невозможности регистрации документа у инцидента ВСЕГДА должен быть проставлен отправитель/получатель. Отсутствие либо отправителя либо получателя приводит к невозможности разобрать инцидент оператором.

![001](https://cloud.githubusercontent.com/assets/6616341/15739592/652f80e4-28b9-11e6-8729-ec493d166a0f.png)

**Comment by ikudin** [comment]
ну смотри. лежит там пустая папка. соответсвенно 2 инцидента: нет файла конверта и нет фала описания. 
ОТКУДА Я ВОЗЬМУ ВСЕХ ИХ???
ну и думаю, что надо выводить ведомство, где зарегистрирован. сейчас этого нет, понять нельзя, где произошло все

**Comment by oknoproblem** [comment]
от туда же откуда ты берёшь получателя либо отправителя во всех остальных случаях, из настроек агента.

**Comment by oknoproblem** [comment]
собственный адрес агента ВСЕГДА доступен, при регистрации инцидента он ВСЕГДА должен быть заполнен.

**Comment by ikudin** [comment]
ты не понимаешь, все дело в сущностях. Если нет данных для создания сущности письма, то эти данные никуда не запишутся и, следовательно, их неоткуда будет взять

**Comment by ikudin** [comment]
в общем, такого никогда не будет. остается вопрос о ведомстве, где возникла заявка. может, будем его отображать?

**Comment by ikudin** [comment]
оно, собственно, и есть отправитель

**Comment by oknoproblem** [comment]
да я тебе об этом и говорю, это ведомство всегда или отправитель или получатель, именно его я и предлагаю отображать... так что это скорее ты не понимаешь... При регистрации инцидента всегда должно быть заполнено ведомство, делай чего хочешь с сущьностями, но если этого не будет, регистрировать инцидент бесполезно.

**Comment by oknoproblem** [comment]
ок
