### ISSUE TITLE
При поиске в справочнике ведомств выводятся не ожидаемые результаты

### ISSUE THREAD

**Issue by oknoproblem** [oknoproblem/medo_agent#69]
При поиске в справочнике ведомств выводятся не ожидаемые результаты

например поиск по 3 выводит записи где нет цифры 3 (я думаю что поиск ведётся не только по отображаемым атрибутам)

![001](https://cloud.githubusercontent.com/assets/6616341/15741168/1e9cddd6-28c1-11e6-8f1c-d5ac81e56363.png)

**Comment by ikudin** [comment]
это, скорее всего, Ид ведомства содержит 3

**Comment by oknoproblem** [comment]
поиск не должен производиться по полю id

**Comment by oknoproblem** [comment]
Теперь не происходит поиска по названию ведомства.
В поиске должены участвовать Полное и краткое названия ведомства и "адрес МЭДО"

**Comment by oknoproblem** [comment]
ок
