### ISSUE TITLE
Не храниться дата появления сообщения в системе МЭДО

### ISSUE THREAD

**Issue by oknoproblem** [oknoproblem/medo_agent#7]
При регистрации сформированного субъектом МЭДО сообщения должны фиксироваться следующие данные:
-	дата и время появления сообщения в системе МЭДО;

шаги:
- отправить любое корректное сообщение типов документ/уведомление

Ожидается:
- в таблице [medo_service].[dbo].[ms_letters] (либо в какой-либо другой) будет зарегистрирована дата регистрации сообщения в системе МЭДО

Получено:
- данная информация отсутствует, либо я не знаю где её искать.

**Comment by oknoproblem** [comment]
зато, зачем то, хранится две даты инцидента "created" и "registred".

**Comment by ikudin** [comment]
данная информация хранится в таблице ms_letters_status. там у письма, появившегося в в системе, будет статус 1.  в таблице соответствие id письма -> id статуса
две даты инцидента:
created - появилось в первый раз
registered - зарегистрировано в последний раз

**Comment by oknoproblem** [comment]
Ясно.
