### ISSUE TITLE
Добавить в описание ошибки разбора xml имя файла в котором обнаружена ошибка (актуально для ТК)

### ISSUE THREAD

**Issue by oknoproblem** [oknoproblem/medo_agent#71]
Добавить в описание ошибки разбора xml имя файла в котором обнаружена ошибка (актуально для ТК)
![001](https://cloud.githubusercontent.com/assets/6616341/15742121/a85d2f5e-28c5-11e6-9522-8632b9a42dcb.png)

**Comment by oknoproblem** [comment]
актуальная бага, каждый инцидент связанный с разбором того или иного файла в пакете сообщения должен содержать информацию с путём до папки. Иначе оператор ГУ никогда не найдёт сообщение.

**Comment by oknoproblem** [comment]
1) При ошибке наличия версии схемы
> В папке tk_001_07 ошибка валидации xml: 
> Файл XSD схемы [D:\MEDO\Portal\Monitoring Agent MEDO\XSD\2.7.xsd] отсутствует
2) При отсутствии файлов указанных в файле описания:
> Папка bad_document_ExtraFilesINI_68B2871F-BC0A-451B-0000-000000000010 не содержит приложенных файлов: 
> NoFileInFolder.tif

Проверь пожалуйста по коду, какие тексты ошибки инцидентов ты генеришь.

**Comment by ikudin** [comment]
сейчвс везде будут полные пути к файлам и папкам

**Comment by oknoproblem** [comment]
ок
