### ISSUE TITLE
Не понятное сообщение при регистрации инцидента (отсутствует содержательная часть)

### ISSUE THREAD

**Issue by oknoproblem** [oknoproblem/medo_agent#8]
Шаги:
- отправть на обработку файл ini с указанием файла отсутствующим в папке

Ожидается:
- в описании инцидента должен быть указан отсутствующий файл

Получено:
- сообщение: 

> Папка 1F87B2680ABC1B45AB5DCF94AA50B82E не содержит приложенных файлов:

без указания какого конкретно файла не хватает

**Comment by ikudin** [comment]
Исправлено

**Comment by oknoproblem** [comment]
Исправлено
