### ISSUE TITLE
При заполнении поля Ведомства в заявке любым произвольным значением кнопка Добавить становится доступна, но реально добавить заявку нельзя.

### ISSUE THREAD

**Issue by oknoproblem** [oknoproblem/medo_agent#81]
При заполнении поля Ведомства в заявке любым произвольным значением кнопка Добавить становится доступна, но реально добавить заявку нельзя.

Происходит это из за того что данное поле должно быть дропдауном с возможностью поиска по подстроке.
![001](https://cloud.githubusercontent.com/assets/6616341/16036082/f322d7a8-3222-11e6-8a03-45035bc910e5.png)

**Comment by ikudin** [comment]
так было же изначально с дропдауном. сделать дропдаун? или просто не активировать кнопку, пока ведомства не будет?

**Comment by oknoproblem** [comment]
дропдаун там необходим, так как поле должно быть уникальным выбором из справочника, но там должен работать поиск и НЕ ДОЛЖЕН работать бэкспейс.

**Comment by ikudin** [comment]
не должен работать для стирания или переходя назад в браузере?)

**Comment by oknoproblem** [comment]
при стирании бэкспейсом не должно происходить перехода назад в браузере.

**Comment by ikudin** [comment]
сделал

**Comment by oknoproblem** [comment]
у меня ничего не поменялось в последней версии

**Comment by ikudin** [comment]
высвечивается ошибка, если просто что-то введено, а ведомство не выбрано.

**Comment by ikudin** [comment]
не от любого, а от разрешенных

**Comment by oknoproblem** [comment]
да не тем пользователем зашёл, а список теперь норм, видимо, что-то с кешем было...
