### ISSUE TITLE
Не правильный порядок статусов. 

### ISSUE THREAD

**Issue by oknoproblem** [oknoproblem/medo_agent#82]
Сначала должен идти "Обрабатывается сервером МЭДО, отправка получателю"
потом "Обрабатывается"
потом "Передано"
потом "Доставлено"

Сейчас первый и второй статусы перепутаны местами.

**Comment by ikudin** [comment]
это все равно, в общем-то. просто надо знать, какой статус в какую папку ставить. но я поправлю

**Comment by oknoproblem** [comment]
Ну как бы это не всё равно, логику надо сохранять, и первый статус не может по порядку идти вторым. По моему это очевидно.

К тому же как будет реализована регистрация инцидентов по письмам с просрочкой статуса?

В общем надо править согласно общечеловеческой логике.

**Comment by ikudin** [comment]
так.
сначала мы забираем письмо у них - это статус обрабатывается. первая папка
потом он отправляется на сервер - вторая папка.
все правильно по-моему

**Comment by oknoproblem** [comment]
Статусы согласованы Надеждой и Андреем, и согласованные статусы идут именно в том порядке в котором я сказал:
"Обрабатывается сервером МЭДО, отправка получателю"
потом "Обрабатывается"
потом "Передано"
потом "Доставлено"

**Comment by ikudin** [comment]
должно сработать,я поля поправил. при миграции должно все исправиться

**Comment by ikudin** [comment]
по-настоящему исправиться при установке на чистую базу. а в данный момент поменяется только порядок статусов.
короче, надо удалить базу совсем и запустить приложение. все будет норм
