### ISSUE TITLE
не происходит фильтрации списка сообщений инцидентов при переходе со вкладки Сводка.

### ISSUE THREAD

**Issue by oknoproblem** [oknoproblem/medo_agent#83]
При клике по элементу списков на вкладке Сводка должен появлятся отфильтрованный список с фокусом на необходимом элементе. Например нажав на заявку в списке Новых (незакрытых) заявок, я должен перейти на карточку заявки. В данный момент я попадаю на последнюю по поступлению заявку.

**Comment by ikudin** [comment]
а у меня переходит на заявку...

**Comment by oknoproblem** [comment]
Да, видимо какой-то глюк был.
