### ISSUE TITLE
Получатель переименовать в Адресат на всех вкладках и элементах интерфейса

### ISSUE THREAD

**Issue by oknoproblem** [oknoproblem/medo_agent#85]
Согласно Прототипу, у элементов системы есть реквизит Адресат, за вместо него на данный момент Получатель. Например:
![001](https://cloud.githubusercontent.com/assets/6616341/16616411/c17c86c6-4385-11e6-85a0-6c54dce89baf.png)

**Comment by ikudin** [comment]
картинка не та, но я везде заменил)

**Comment by oknoproblem** [comment]
ок
