### ISSUE TITLE
Текст "Классификационные системы управления" должен быть ссылкой на Классификатор

### ISSUE THREAD

**Issue by oknoproblem** [oknoproblem/medo_agent#86]
Текст "Классификационные системы управления" должен быть ссылкой на Классификатор

В данный момент это просто текст в футере.

**Comment by ikudin** [comment]
ну тут уж извините, его как такого нет, так что адреса не будет, даже если попросите)))
сделаю просто ссылкой.

**Comment by oknoproblem** [comment]
ок
