### ISSUE TITLE
В шапке сайта должно отображаться Полное имя пользователя, а не логин. А так же должна отображаться Роль пользователя рядом с именем.

### ISSUE THREAD

**Issue by oknoproblem** [oknoproblem/medo_agent#87]
В шапке сайта должно отображаться ФИО пользователя, а не логин. А так же должна отображаться Роль пользователя рядом с именем.

Соответственно ФИО должно быть обязательным к заполнению.

![001](https://cloud.githubusercontent.com/assets/6616341/16616547/90272558-4386-11e6-87a6-2326c6ca3e04.png)

**Comment by ikudin** [comment]
Мы это обсуждали, решили сделать так, как есть сейчас.

**Comment by oknoproblem** [comment]
Мы это кто?
Я этого не обсуждал, в прототипе так как написал я.

**Comment by ikudin** [comment]
Мы - это  мы с тобой и Надежда

**Comment by ikudin** [comment]
Решили так потому что имя может быть довольно длинным вместе с ролью

**Comment by oknoproblem** [comment]
Не помню этого обсуждения, и не вижу проблемы в длинном имени. Там вроде места хватает.

**Comment by oknoproblem** [comment]
ок
