### ISSUE TITLE
Замечания по вёрстке вкладки "Сводка"

### ISSUE THREAD

**Issue by oknoproblem** [oknoproblem/medo_agent#88]
см скрин
![001](https://cloud.githubusercontent.com/assets/6616341/16616912/1f950f6e-4389-11e6-8e42-ae47077caa83.png)

**Comment by ikudin** [comment]
частично сделано

**Comment by ikudin** [comment]
здесь все норм, непонятно только, что с датой надо сделать. вроде по центру все.

**Comment by oknoproblem** [comment]
ок
