### ISSUE TITLE
Регистрировать по одному "документу" на каждого получателя сообщения из файла ini не совсем корректно

### ISSUE THREAD

**Issue by oknoproblem** [oknoproblem/medo_agent#9]
шаги:
- указав в файле ini несколько (более одного) получателей положить корректное сообщение в папку отправленные

Ожидается:
- Регистрация только одного сообщения в БД

Получено:
- регистрация нескольких сообщений кратное кол-ву получателей в файле ini

ПС: В данном случае, количество записей в БД будет расти по экспоненте. Так как будут приходит уведомления, квитанции и тд и тп на одно отправленное письмо. Считаю, что поле reciever должно быть списком получателей.

**Comment by ikudin** [comment]
как все происходит:
1. на каждого получателя генерируется одна запись в ms_letters с информацией о письме и в поле receiver - email получателя.
2. в таблице ms_letter_status добавляется запись о том, что для всех этих получателей письмо имеет статус 1.
3.при получении письма адресатом происходит поиск в БД по uid письма, получателю и отправителю и к найденному письму добавляются статусы.

если поле receiver будет списком получателей, то как мы отследим доставку до конкретного получателя? не, можно, конечно, придумать любую структуру. то есть если поле receiver будет списком, то тогда в таблице статусов надо будет писать email, от кого получен этот статус, а уже потом делать представление в БД через like (т.к. в поле receiver несколько получателей) и это представление будет работать долго. вот.

**Comment by oknoproblem** [comment]
Я понял, т.е. если дважды отправить одно и то же письмо, то дубля создаваться не должно, а вместо этого должен создаваться повторный статус?

**Comment by ikudin** [comment]
а вот с этим я еще думаю. пока что сделано так, что будет создаваться дубль. я, кстати говоря, задавал вопрос по этому поводу (о том, что делать, если повторно отправлено письмо)

В результате я, скорее всего, сделаю так, что дубля создаваться не будет, а будет повторный статус, как Вы и сказали.

**Comment by ikudin** [comment]
сделано

**Comment by oknoproblem** [comment]
Иван, из предложенного вами решение в письме, напомню:

> Отправитель отправил письмо, оно переместилось к вам на монопак. Оно отметилось у нас в БД, как принятое от отправителя. Далее оно пошло отправляться ко всем адресатам и т.д. Какому-либо адресату оно не дошло и его решили отправить повторно и из архива папку с письмом переложили в папку на отправку. Для повторного письма будут создаваться те же статусы (и на него будут отправляться те же квитанции), что и для исходного письма. каким образом различать исходное и отправленное повторно письма? 
> Предлагаемое решение: 
> Для всех писем с одинаковыми атрибутами считать общими все квитанции, уведомления и статусы. то есть если 2 раза было принято какое-либо уведомление или 2 раза был отмечен какой-либо статус, то его же 2 раза отмечать. а для самого письма добавить счетчик кол-ва отправлений. 

Считаю необходимо сделать так:
при получении письма с повторным guid

**Comment by ikudin** [comment]
так оно и есть. попробуйте отправить одно и то же письмо 2 раза.
за кол-во отправок отвевчает поле send_count в таблице ms_letters

**Comment by oknoproblem** [comment]
пока закрою
