### ISSUE TITLE
Вёрстка вкладки "Сообщения" замечания

### ISSUE THREAD

**Issue by oknoproblem** [oknoproblem/medo_agent#90]
Вёрстка вкладки "Сообщения" замечания:
![001](https://cloud.githubusercontent.com/assets/6616341/16623578/31483d3a-43a7-11e6-8a27-285e935408de.png)

**Comment by ikudin** [comment]
есть предложение вынести кнопку очистить в правую часть серой области вровень с Поиск сообщений. тогда и в свернутом виде можно будет очистить поиск)
и так везде сделать. остальное сделал

**Comment by oknoproblem** [comment]
вынести можно, но после сдачи проекта. Пока оставляем как есть.
