### ISSUE TITLE
Не добавляется комментарий у заявок/инцидентов

### ISSUE THREAD

**Issue by oknoproblem** [oknoproblem/medo_agent#95]
шаги:
- перейти на вкладку Инциденты и заявки (обновить страницу если вкладка уже была открыта)
- добавить текст комментария (файлы не прикреплять)
- нажать кнопку Добавить комментарий

Ожидается:
- комментарий добавился
- страница обновилась показывая добавленный комментарий

Получено:
- добавленный коментарий видно только после обновления страницы.

ПС: В случае если к комментарий приложен файл, комментарий добавляется корректно и все последующие так же добавляются корректно даже без файлов.

**Comment by ikudin** [comment]
повторить не удалось, все отрабатывает так, как ожидалось

**Comment by oknoproblem** [comment]
видимо в моей прошлой версии была проблема, сейчас нет.

ок
