### ISSUE TITLE
У заявок и инцидентов должны быть собственные справочники статусов

### ISSUE THREAD

**Issue by oknoproblem** [oknoproblem/medo_agent#98]
У заявок и инцидентов должны быть собственные справочники статусов

Должно быть:
Статус в Заявки "Поступила"
Статус у Инцидента "Поступил"

Сейчас и там и так "Поступила". Склонение по родам должно быть.

**Comment by oknoproblem** [comment]
то же с "Зарегистрирована"

**Comment by oknoproblem** [comment]
то же с "Создана"

**Comment by oknoproblem** [comment]
то же с "Выполнена"

**Comment by oknoproblem** [comment]
Просьба внимательнее исправлять дефекты, если не знаешь где указанная проблема, закрывать задачу нельзя, необходимо спросить где проблема.

**Comment by oknoproblem** [comment]
Инцидент:
![001](https://cloud.githubusercontent.com/assets/6616341/17131913/19eee216-5328-11e6-9c1c-a2d20e9cb993.png)

**Comment by oknoproblem** [comment]
Заявка:
Ок, на данный момент.

**Comment by ikudin** [comment]
не понял. Все норм?

**Comment by oknoproblem** [comment]
для заявок всё ок, для инцидентов смотри последний коммент со скриншотом.

**Comment by oknoproblem** [comment]
ok
